**Tensors**

Tensors adalah struktur data khusus yang sangat mirip dengan array dan matriks. Di PyTorch, kita menggunakan tensors untuk mengkodekan input dan output dari sebuah model, serta parameter-parameternya.

Tensors mirip dengan ndarray milik NumPy, tetapi tensors dapat berjalan di GPU atau akselerator perangkat keras lainnya. Bahkan, tensors dan array NumPy seringkali dapat berbagi memori yang sama, menghilangkan kebutuhan untuk menyalin data (lihat Bridge with NumPy). Tensors juga dioptimalkan untuk diferensiasi otomatis (kita akan melihat lebih lanjut tentang ini nanti di bagian Autograd). Jika Anda sudah familiar dengan ndarray, Anda akan merasa nyaman dengan Tensor API. Jika tidak, ikuti terus!

In [11]:
# Import Pandas dan Pytorch (Untuk import Pytorch syntax nya adalah import torch) 

import torch
import numpy as np

Setelah Import Apa yang akan kita lakukan ? mari kita membuat tensor sederhana pertama kita

In [2]:
# Membuat tensor pertama 

tensor = torch.tensor(1)
tensor

tensor(1)

Tensor pertama telah dibuat, lalu bagaimana cara membuat tensor untuk multidimensi ?

In [8]:
# Membuat tensor multidimensi
tensor_1 = torch.tensor([[1,2],[4,5]])
tensor_1

tensor([[1, 2],
        [4, 5]])

Pytorch juga menyediakan syntax khusus seperti "random" dan "ones" untuk membuat tensor

In [12]:
# Membuat tensor one_like

tensor_ones = torch.ones_like(tensor_1)
tensor_ones

tensor([[1, 1],
        [1, 1]])

Yang dilakukan "ones_like" adalah membuat semua yang ada dalam tensor_1 menjadi angka 1

kita juga bisa membuat dimensi yang sama seperti "tensor_1" namun dengan angka yang random

In [14]:
# Membuat tensor rand_like

tensor_random = torch.rand_like(tensor_1,dtype=torch.float)
tensor_random

tensor([[0.7687, 0.2569],
        [0.8656, 0.9102]])

Sedikit breakdown mengenai code diatas : 

- torch.rand_like mengikuti dimensi dari tensor_1
- dtype = kita membuat tipe data apa yang akan dimuat pada tensor_random (pada kasus kali ini adalah float)
- bisa dilihat kita mengikuti dimensi seperti tensor_1 namun dengan value / isi yang berbeda

Kita juga bisa hanya membuat shape nya saja lalu biarkan torch yang bekerja untuk membuat dummy value

- kita akan menggunakan one (untuk membuat value nya berisi "1" dengan shape yang akan kita buat)
- kita akan menggunakan random (untuk membuat value nya berisi random dengan shape yang akan kita buat)
- kita akan menggunakan zero (untuk membuat value nya berisi "0" dengan shape yang akan kita buat)

In [20]:
# Membuat shape terlebih dahulu : kita akan menggunakan matriks 3x3
shape = (3,3)

# Membuat tensor dengan value 1
one_tensor = torch.ones(shape)

# Membuat tensor dengan value random
rand_tensor = torch.rand(shape)

# Membuat tensor dengan value zero
zero_tensor = torch.zeros(shape)

# Mari kita print hasilnya
print(f"Hasil one tensor :\n {one_tensor}")
print(f"Hasil random tensor :\n {rand_tensor}")
print(f"Hasil zero tensor :\n {zero_tensor}")

Hasil one tensor :
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Hasil random tensor :
 tensor([[0.9461, 0.3979, 0.4713],
        [0.7021, 0.6030, 0.0096],
        [0.2158, 0.1349, 0.1658]])
Hasil zero tensor :
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Kita bisa melihat bahwa semua nya terbentuk mengikuti shape yang telah kita tentukan, namun bagaimana kita bisa check shape dari masing masing tensor ? kita bisa menggunakan variable.shape

In [21]:
print(f"One Tensor Shape : {one_tensor.shape}")
print(f"Random Tensor Shape : {rand_tensor.shape}")
print(f"Zero Tensor Shape : {zero_tensor.shape}")

One Tensor Shape : torch.Size([3, 3])
Random Tensor Shape : torch.Size([3, 3])
Zero Tensor Shape : torch.Size([3, 3])


Bisa kita lihat bahwa shape nya sudah sesuai, yaitu matriks 3x3 atau sama dengan 3,3

Kita juga bisa menggunakan menampilkan hanya index keberapa dari tensor yang telah kita buat, caranya sama seperti array   

In [22]:
one_tensor[0]

tensor([1., 1., 1.])

In [23]:
rand_tensor[0]

tensor([0.9461, 0.3979, 0.4713])

In [24]:
zero_tensor[0]

tensor([0., 0., 0.])

Masih banyak hal yang bisa dilakukan oleh tensor, namun sebaiknya kita mulai membuat model agar dapat menerapkan praktik penggunaan tensor secara langsung.